version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./key.json:/envs/key.json
    environment:
      - PUBLIC_HOST=0.0.0.0
      - GOOGLE_CONFIG_PATH=/envs/key.json
    networks:
      - api-network

networks:
  api-network:
    driver: bridge
